/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/localhost/Downloads/parted-3.7/out"
#define EXEC_PREFIX "/home/localhost/Downloads/parted-3.7/out"
#define BINDIR "/home/localhost/Downloads/parted-3.7/out/bin"
#define SBINDIR "/home/localhost/Downloads/parted-3.7/out/sbin"
#define LIBEXECDIR "/home/localhost/Downloads/parted-3.7/out/libexec"
#define DATAROOTDIR "/home/localhost/Downloads/parted-3.7/out/share"
#define DATADIR "/home/localhost/Downloads/parted-3.7/out/share"
#define SYSCONFDIR "/home/localhost/Downloads/parted-3.7/out/etc"
#define SHAREDSTATEDIR "/home/localhost/Downloads/parted-3.7/out/com"
#define LOCALSTATEDIR "/home/localhost/Downloads/parted-3.7/out/var"
#define RUNSTATEDIR "/home/localhost/Downloads/parted-3.7/out/var/run"
#define INCLUDEDIR "/home/localhost/Downloads/parted-3.7/out/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/localhost/Downloads/parted-3.7/out/share/doc/parted"
#define INFODIR "/home/localhost/Downloads/parted-3.7/out/share/info"
#define HTMLDIR "/home/localhost/Downloads/parted-3.7/out/share/doc/parted"
#define DVIDIR "/home/localhost/Downloads/parted-3.7/out/share/doc/parted"
#define PDFDIR "/home/localhost/Downloads/parted-3.7/out/share/doc/parted"
#define PSDIR "/home/localhost/Downloads/parted-3.7/out/share/doc/parted"
#define LIBDIR "/home/localhost/Downloads/parted-3.7/out/lib"
#define LISPDIR "/home/localhost/Downloads/parted-3.7/out/share/emacs/site-lisp"
#define LOCALEDIR "/home/localhost/Downloads/parted-3.7/out/share/locale"
#define MANDIR "/home/localhost/Downloads/parted-3.7/out/share/man"
#define PKGDATADIR "/home/localhost/Downloads/parted-3.7/out/share/parted"
#define PKGINCLUDEDIR "/home/localhost/Downloads/parted-3.7/out/include/parted"
#define PKGLIBDIR "/home/localhost/Downloads/parted-3.7/out/lib/parted"
#define PKGLIBEXECDIR "/home/localhost/Downloads/parted-3.7/out/libexec/parted"
